### ISSUE TITLE
remove_duplicates.py

### ISSUE THREAD

**Issue by cwcrowel** [adrienmonks/Group-#12]
Description: There is a syntax error on line 15 of remove_duplicates.py. The parameter is incorrectly typed into the program.

Steps to Reproduce

1. Setup the statement "unique_arr, removed_elements = remove_duplicates()"
2. Inside the parameter, type "arr"
3. Instead of stopping after 2 r's, continue holding down the r key until you have 42 of them

Expected Behavior: I expected there to be an "arr" inside the parentheses.

Actual Behavior: There was an "arrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr" inside the parentheses.

Additional Information

Operating System: MacOS
Browser: Chrome
Version: 109.0.5414.87

Any other relevant information

Possible Solution: Replacing "arrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr" with "arr" inside the parentheses of line 15.

Priority: Low

Reproducibility: This bug could always be reproduced because a syntax error does not relate to functionality of the program leading up to that line.

Impact: The impact of this bug if high, because the program cannot run this line.

**Comment by mgohacki** [comment]
fixed
