### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by akaplan521** [adrienmonks/Group-#9]
There is a syntax error in remove_duplicates.cc on line number 8
Steps to Reproduce

First step to reproduce the issue/bug
Second step to reproduce the issue/bug
Third step to reproduce the issue/bug
Expected Behavior A clear and concise description of what you expected to happen.

Actual Behavior A clear and concise description of what actually happened.
Screenshots If applicable, add screenshots to help explain the issue/bug.

Additional Information

Operating System: Windows
Browser: Chrome
Version: 111.0.5563.64
Any other relevant information
Possible Solution If you have any suggestions for a possible solution, please include them here.
Adding a ';'? Adding a '}' character?
Related Issues Are there any related issues? If so, please link to them here.
NO.
Priority How critical is this issue/bug? Low, medium, or high priority?
VERY CRITICAL PLEASE HELP
Reproducibility How often can this issue/bug be reproduced? Always, sometimes, or random?
Always because this is a syntax issue. 
Impact What is the impact of this issue/bug? Low, medium, or high?

**Comment by adrienmonks** [comment]
Added ; to line 8 and } to line 14
